export const custom_data = {
    data: [
      {
        action: "Track",
        actiontype: "booked",
        actual_departure: "",
        actuval_arrival: "",
        booked_on: "01-OCT-24",
        booking_link: "http://fslgo.com",
        consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
        destination: "Jebel Ali (AEJEA)",
        destination_countrycode: "KW",
        estimated_arrival: "",
        estimated_departure: "",
        "eta/ata": "27-OCT-24",
        eta_ata: "01 Oct 2024",
        "etd/atd": "27-OCT-24",
        etd_atd: "01 Oct 2024",
        hbl_number: "120624000795",
        id: "150294001303",
        container_id: "40 GP | TEMU6052410",
        is_updated: "",
        milestones: [],
        mode: "22 Sep 2024",
        order_no: "18 Sep 2024",
        origin: "Singapore",
        origin_countrycode: "SG",
        shipper_name: "SEGA MECHELEC",
        notify_name: "Abs",
        status: "Partialy Completed",
        tos: "EX WORKS",
        updated_message: "Test",
        valid_date: "15-Jun-2024",
      },
      {
        action: "Track",
        actiontype: "booked",
        actual_departure: "",
        actuval_arrival: "",
        booked_on: "01-OCT-24",
        booking_link: "http://fslgo.com",
        consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
        destination: "Jebel Ali (AEJEA)",
        destination_countrycode: "KW",
        estimated_arrival: "",
        estimated_departure: "",
        "eta/ata": "27-OCT-24",
        eta_ata: "01 Oct 2024",
        "etd/atd": "27-OCT-24",
        etd_atd: "01 Oct 2024",
        hbl_number: "120624000795",
        id: "150294001303",
        container_id: "40 GP | TEMU6052410",
        is_updated: "",
        milestones: [],
        mode: "22 Sep 2024",
        order_no: "18 Sep 2024",
        origin: "Singapore",
        origin_countrycode: "SG",
        shipper_name: "SEGA MECHELEC",
        notify_name: "Abs",
        status: "completed",
        tos: "EX WORKS",
        updated_message: "Test",
        valid_date: "15-Jun-2024",
      },
      {
        action: "Track",
        actiontype: "booked",
        actual_departure: "",
        actuval_arrival: "",
        booked_on: "01-OCT-24",
        booking_link: "http://fslgo.com",
        consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
        destination: "Jebel Ali (AEJEA)",
        destination_countrycode: "KW",
        estimated_arrival: "",
        estimated_departure: "",
        "eta/ata": "27-OCT-24",
        eta_ata: "01 Oct 2024",
        "etd/atd": "27-OCT-24",
        etd_atd: "01 Oct 2024",
        hbl_number: "120624000795",
        id: "150294001303",
        container_id: "40 GP | TEMU6052410",
        is_updated: "",
        milestones: [],
        mode: "22 Sep 2024",
        order_no: "18 Sep 2024",
        origin: "Singapore",
        origin_countrycode: "SG",
        shipper_name: "SEGA MECHELEC",
        notify_name: "Abs",
        status: "Partially Completed",
        tos: "EX WORKS",
        updated_message: "Test",
        valid_date: "15-Jun-2024",
      },
      {
        action: "Track",
        actiontype: "booked",
        actual_departure: "",
        actuval_arrival: "",
        booked_on: "01-OCT-24",
        booking_link: "http://fslgo.com",
        consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
        destination: "Jebel Ali (AEJEA)",
        destination_countrycode: "KW",
        estimated_arrival: "",
        estimated_departure: "",
        "eta/ata": "27-OCT-24",
        eta_ata: "01 Oct 2024",
        "etd/atd": "27-OCT-24",
        etd_atd: "01 Oct 2024",
        hbl_number: "120624000795",
        id: "150294001303",
        container_id: "40 GP | TEMU6052410",
        is_updated: "",
        milestones: [],
        mode: "22 Sep 2024",
        order_no: "18 Sep 2024",
        origin: "Singapore",
        origin_countrycode: "SG",
        shipper_name: "SEGA MECHELEC",
        notify_name: "Abs",
        status: "Completed",
        tos: "EX WORKS",
        updated_message: "Test",
        valid_date: "15-Jun-2024",
      },
      {
        action: "Track",
        actiontype: "booked",
        actual_departure: "",
        actuval_arrival: "",
        booked_on: "01-OCT-24",
        booking_link: "http://fslgo.com",
        consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
        destination: "Jebel Ali (AEJEA)",
        destination_countrycode: "KW",
        estimated_arrival: "",
        estimated_departure: "",
        "eta/ata": "27-OCT-24",
        eta_ata: "01 Oct 2024",
        "etd/atd": "27-OCT-24",
        etd_atd: "01 Oct 2024",
        hbl_number: "120624000795",
        id: "150294001303",
        container_id: "40 GP | TEMU6052410",
        is_updated: "",
        milestones: [],
        mode: "22 Sep 2024",
        order_no: "18 Sep 2024",
        origin: "Singapore",
        origin_countrycode: "SG",
        shipper_name: "SEGA MECHELEC",
        notify_name: "Abs",
        status: "Partially Completed",
        tos: "EX WORKS",
        updated_message: "Test",
        valid_date: "15-Jun-2024",
      },
      {
        action: "Track",
        actiontype: "booked",
        actual_departure: "",
        actuval_arrival: "",
        booked_on: "01-OCT-24",
        booking_link: "http://fslgo.com",
        consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
        destination: "Jebel Ali (AEJEA)",
        destination_countrycode: "KW",
        estimated_arrival: "",
        estimated_departure: "",
        "eta/ata": "27-OCT-24",
        eta_ata: "01 Oct 2024",
        "etd/atd": "27-OCT-24",
        etd_atd: "01 Oct 2024",
        hbl_number: "120624000795",
        id: "150294001303",
        container_id: "40 GP | TEMU6052410",
        is_updated: "",
        milestones: [],
        mode: "22 Sep 2024",
        order_no: "18 Sep 2024",
        origin: "Singapore",
        origin_countrycode: "SG",
        shipper_name: "SEGA MECHELEC",
        notify_name: "Abs",
        status: "Completed",
        tos: "EX WORKS",
        updated_message: "Test",
        valid_date: "15-Jun-2024",
      }
      ,{
      action: "Track",
      actiontype: "booked",
      actual_departure: "",
      actuval_arrival: "",
      booked_on: "01-OCT-24",
      booking_link: "http://fslgo.com",
      consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
      destination: "Jebel Ali (AEJEA)",
      destination_countrycode: "KW",
      estimated_arrival: "",
      estimated_departure: "",
      "eta/ata": "27-OCT-24",
      eta_ata: "01 Oct 2024",
      "etd/atd": "27-OCT-24",
      etd_atd: "01 Oct 2024",
      hbl_number: "120624000795",
      id: "150294001303",
      container_id: "40 GP | TEMU6052410",
      is_updated: "",
      milestones: [],
      mode: "22 Sep 2024",
      order_no: "18 Sep 2024",
      origin: "Singapore",
      origin_countrycode: "SG",
      shipper_name: "SEGA MECHELEC",
      notify_name: "Abs",
      status: "Partially Completed",
      tos: "EX WORKS",
      updated_message: "Test",
      valid_date: "15-Jun-2024",
    }
      ,{
      action: "Track",
      actiontype: "booked",
      actual_departure: "",
      actuval_arrival: "",
      booked_on: "01-OCT-24",
      booking_link: "http://fslgo.com",
      consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
      destination: "Jebel Ali (AEJEA)",
      destination_countrycode: "KW",
      estimated_arrival: "",
      estimated_departure: "",
      "eta/ata": "27-OCT-24",
      eta_ata: "01 Oct 2024",
      "etd/atd": "27-OCT-24",
      etd_atd: "01 Oct 2024",
      hbl_number: "120624000795",
      id: "150294001303",
      container_id: "40 GP | TEMU6052410",
      is_updated: "",
      milestones: [],
      mode: "22 Sep 2024",
      order_no: "18 Sep 2024",
      origin: "Singapore",
      origin_countrycode: "SG",
      shipper_name: "SEGA MECHELEC",
      notify_name: "Abs",
      status: "Partially Completed",
      tos: "EX WORKS",
      updated_message: "Test",
      valid_date: "15-Jun-2024",
    }
      ,{
      action: "Track",
      actiontype: "booked",
      actual_departure: "",
      actuval_arrival: "",
      booked_on: "01-OCT-24",
      booking_link: "http://fslgo.com",
      consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
      destination: "Jebel Ali (AEJEA)",
      destination_countrycode: "KW",
      estimated_arrival: "",
      estimated_departure: "",
      "eta/ata": "27-OCT-24",
      eta_ata: "01 Oct 2024",
      "etd/atd": "27-OCT-24",
      etd_atd: "01 Oct 2024",
      hbl_number: "120624000795",
      id: "150294001303",
      container_id: "40 GP | TEMU6052410",
      is_updated: "",
      milestones: [],
      mode: "22 Sep 2024",
      order_no: "18 Sep 2024",
      origin: "Singapore",
      origin_countrycode: "SG",
      shipper_name: "SEGA MECHELEC",
      notify_name: "Abs",
      status: "Partially Completed",
      tos: "EX WORKS",
      updated_message: "Test",
      valid_date: "15-Jun-2024",
    }
      ,{
      action: "Track",
      actiontype: "booked",
      actual_departure: "",
      actuval_arrival: "",
      booked_on: "01-OCT-24",
      booking_link: "http://fslgo.com",
      consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
      destination: "Jebel Ali (AEJEA)",
      destination_countrycode: "KW",
      estimated_arrival: "",
      estimated_departure: "",
      "eta/ata": "27-OCT-24",
      eta_ata: "01 Oct 2024",
      "etd/atd": "27-OCT-24",
      etd_atd: "01 Oct 2024",
      hbl_number: "120624000795",
      id: "150294001303",
      container_id: "40 GP | TEMU6052410",
      is_updated: "",
      milestones: [],
      mode: "22 Sep 2024",
      order_no: "18 Sep 2024",
      origin: "Singapore",
      origin_countrycode: "SG",
      shipper_name: "SEGA MECHELEC",
      notify_name: "Abs",
      status: "Partially Completed",
      tos: "EX WORKS",
      updated_message: "Test",
      valid_date: "15-Jun-2024",
    }
      ,{
      action: "Track",
      actiontype: "booked",
      actual_departure: "",
      actuval_arrival: "",
      booked_on: "01-OCT-24",
      booking_link: "http://fslgo.com",
      consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
      destination: "Jebel Ali (AEJEA)",
      destination_countrycode: "KW",
      estimated_arrival: "",
      estimated_departure: "",
      "eta/ata": "27-OCT-24",
      eta_ata: "01 Oct 2024",
      "etd/atd": "27-OCT-24",
      etd_atd: "01 Oct 2024",
      hbl_number: "120624000795",
      id: "150294001303",
      container_id: "40 GP | TEMU6052410",
      is_updated: "",
      milestones: [],
      mode: "22 Sep 2024",
      order_no: "18 Sep 2024",
      origin: "Singapore",
      origin_countrycode: "SG",
      shipper_name: "SEGA MECHELEC",
      notify_name: "Abs",
      status: "Partially Completed",
      tos: "EX WORKS",
      updated_message: "Test",
      valid_date: "15-Jun-2024",
    }
      ,{
      action: "Track",
      actiontype: "booked",
      actual_departure: "",
      actuval_arrival: "",
      booked_on: "01-OCT-24",
      booking_link: "http://fslgo.com",
      consignee_name: "AL AHLEIA SWITCHGEAR CO., K.S.C.C.[SAFAT]",
      destination: "Jebel Ali (AEJEA)",
      destination_countrycode: "KW",
      estimated_arrival: "",
      estimated_departure: "",
      "eta/ata": "27-OCT-24",
      eta_ata: "01 Oct 2024",
      "etd/atd": "27-OCT-24",
      etd_atd: "01 Oct 2024",
      hbl_number: "120624000795",
      id: "150294001303",
      container_id: "40 GP | TEMU6052410",
      is_updated: "",
      milestones: [],
      mode: "22 Sep 2024",
      order_no: "18 Sep 2024",
      origin: "Singapore",
      origin_countrycode: "SG",
      shipper_name: "SEGA MECHELEC",
      notify_name: "Abs",
      status: "Partially Completed",
      tos: "EX WORKS",
      updated_message: "Test",
      valid_date: "15-Jun-2024",
    }
      
    ],
    statuswise_count: [
      {
        booked: "7",
        delivered: "26",
        arrived: "1",
        all: "34",
      },
    ],
  };
  